// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/industrial-sed/auth-service/internal/ports (interfaces: KeycloakClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/keycloak.go -package=mocks github.com/industrial-sed/auth-service/internal/ports KeycloakClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gocloak "github.com/Nerzal/gocloak/v13"
	ports "github.com/industrial-sed/auth-service/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockKeycloakClient is a mock of KeycloakClient interface.
type MockKeycloakClient struct {
	ctrl     *gomock.Controller
	recorder *MockKeycloakClientMockRecorder
}

// MockKeycloakClientMockRecorder is the mock recorder for MockKeycloakClient.
type MockKeycloakClientMockRecorder struct {
	mock *MockKeycloakClient
}

// NewMockKeycloakClient creates a new mock instance.
func NewMockKeycloakClient(ctrl *gomock.Controller) *MockKeycloakClient {
	mock := &MockKeycloakClient{ctrl: ctrl}
	mock.recorder = &MockKeycloakClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeycloakClient) EXPECT() *MockKeycloakClientMockRecorder {
	return m.recorder
}

// AddRealmRoleToUser mocks base method.
func (m *MockKeycloakClient) AddRealmRoleToUser(arg0 context.Context, arg1, arg2 string, arg3 []gocloak.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRealmRoleToUser", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRealmRoleToUser indicates an expected call of AddRealmRoleToUser.
func (mr *MockKeycloakClientMockRecorder) AddRealmRoleToUser(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRealmRoleToUser", reflect.TypeOf((*MockKeycloakClient)(nil).AddRealmRoleToUser), arg0, arg1, arg2, arg3)
}

// AddUserToGroup mocks base method.
func (m *MockKeycloakClient) AddUserToGroup(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroup", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockKeycloakClientMockRecorder) AddUserToGroup(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockKeycloakClient)(nil).AddUserToGroup), arg0, arg1, arg2, arg3)
}

// CountUsersByUsername mocks base method.
func (m *MockKeycloakClient) CountUsersByUsername(arg0 context.Context, arg1, arg2 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsersByUsername", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsersByUsername indicates an expected call of CountUsersByUsername.
func (mr *MockKeycloakClientMockRecorder) CountUsersByUsername(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsersByUsername", reflect.TypeOf((*MockKeycloakClient)(nil).CountUsersByUsername), arg0, arg1, arg2)
}

// CreateGroup mocks base method.
func (m *MockKeycloakClient) CreateGroup(arg0 context.Context, arg1, arg2 string, arg3 map[string][]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockKeycloakClientMockRecorder) CreateGroup(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockKeycloakClient)(nil).CreateGroup), arg0, arg1, arg2, arg3)
}

// CreateUser mocks base method.
func (m *MockKeycloakClient) CreateUser(arg0 context.Context, arg1 string, arg2 gocloak.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockKeycloakClientMockRecorder) CreateUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockKeycloakClient)(nil).CreateUser), arg0, arg1, arg2)
}

// DeleteGroup mocks base method.
func (m *MockKeycloakClient) DeleteGroup(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockKeycloakClientMockRecorder) DeleteGroup(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockKeycloakClient)(nil).DeleteGroup), arg0, arg1, arg2)
}

// DeleteUser mocks base method.
func (m *MockKeycloakClient) DeleteUser(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockKeycloakClientMockRecorder) DeleteUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockKeycloakClient)(nil).DeleteUser), arg0, arg1, arg2)
}

// EndSessionURL mocks base method.
func (m *MockKeycloakClient) EndSessionURL(arg0, arg1 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndSessionURL", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// EndSessionURL indicates an expected call of EndSessionURL.
func (mr *MockKeycloakClientMockRecorder) EndSessionURL(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndSessionURL", reflect.TypeOf((*MockKeycloakClient)(nil).EndSessionURL), arg0, arg1)
}

// EnsureOAuthClient mocks base method.
func (m *MockKeycloakClient) EnsureOAuthClient(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureOAuthClient", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureOAuthClient indicates an expected call of EnsureOAuthClient.
func (mr *MockKeycloakClientMockRecorder) EnsureOAuthClient(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureOAuthClient", reflect.TypeOf((*MockKeycloakClient)(nil).EnsureOAuthClient), arg0, arg1, arg2)
}

// EnsureRealmAndRoles mocks base method.
func (m *MockKeycloakClient) EnsureRealmAndRoles(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureRealmAndRoles", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureRealmAndRoles indicates an expected call of EnsureRealmAndRoles.
func (mr *MockKeycloakClientMockRecorder) EnsureRealmAndRoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureRealmAndRoles", reflect.TypeOf((*MockKeycloakClient)(nil).EnsureRealmAndRoles), arg0, arg1)
}

// EnsureUserAttributeMapper mocks base method.
func (m *MockKeycloakClient) EnsureUserAttributeMapper(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureUserAttributeMapper", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureUserAttributeMapper indicates an expected call of EnsureUserAttributeMapper.
func (mr *MockKeycloakClientMockRecorder) EnsureUserAttributeMapper(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureUserAttributeMapper", reflect.TypeOf((*MockKeycloakClient)(nil).EnsureUserAttributeMapper), arg0, arg1)
}

// ExchangeCode mocks base method.
func (m *MockKeycloakClient) ExchangeCode(arg0 context.Context, arg1, arg2, arg3 string) (*ports.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*ports.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockKeycloakClientMockRecorder) ExchangeCode(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockKeycloakClient)(nil).ExchangeCode), arg0, arg1, arg2, arg3)
}

// FindUsers mocks base method.
func (m *MockKeycloakClient) FindUsers(arg0 context.Context, arg1, arg2 string) ([]*gocloak.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsers", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*gocloak.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsers indicates an expected call of FindUsers.
func (mr *MockKeycloakClientMockRecorder) FindUsers(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsers", reflect.TypeOf((*MockKeycloakClient)(nil).FindUsers), arg0, arg1, arg2)
}

// GetGroupByPath mocks base method.
func (m *MockKeycloakClient) GetGroupByPath(arg0 context.Context, arg1, arg2 string) (*gocloak.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByPath", arg0, arg1, arg2)
	ret0, _ := ret[0].(*gocloak.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByPath indicates an expected call of GetGroupByPath.
func (mr *MockKeycloakClientMockRecorder) GetGroupByPath(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByPath", reflect.TypeOf((*MockKeycloakClient)(nil).GetGroupByPath), arg0, arg1, arg2)
}

// GetRealmRolesOfUser mocks base method.
func (m *MockKeycloakClient) GetRealmRolesOfUser(arg0 context.Context, arg1, arg2 string) ([]*gocloak.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRealmRolesOfUser", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*gocloak.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRealmRolesOfUser indicates an expected call of GetRealmRolesOfUser.
func (mr *MockKeycloakClientMockRecorder) GetRealmRolesOfUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRealmRolesOfUser", reflect.TypeOf((*MockKeycloakClient)(nil).GetRealmRolesOfUser), arg0, arg1, arg2)
}

// GetUserByID mocks base method.
func (m *MockKeycloakClient) GetUserByID(arg0 context.Context, arg1, arg2 string) (*gocloak.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*gocloak.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockKeycloakClientMockRecorder) GetUserByID(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockKeycloakClient)(nil).GetUserByID), arg0, arg1, arg2)
}

// GetUsersInGroup mocks base method.
func (m *MockKeycloakClient) GetUsersInGroup(arg0 context.Context, arg1, arg2 string) ([]*gocloak.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersInGroup", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*gocloak.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersInGroup indicates an expected call of GetUsersInGroup.
func (mr *MockKeycloakClientMockRecorder) GetUsersInGroup(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersInGroup", reflect.TypeOf((*MockKeycloakClient)(nil).GetUsersInGroup), arg0, arg1, arg2)
}

// LoginAdmin mocks base method.
func (m *MockKeycloakClient) LoginAdmin(arg0 context.Context) (*gocloak.JWT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginAdmin", arg0)
	ret0, _ := ret[0].(*gocloak.JWT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginAdmin indicates an expected call of LoginAdmin.
func (mr *MockKeycloakClientMockRecorder) LoginAdmin(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginAdmin", reflect.TypeOf((*MockKeycloakClient)(nil).LoginAdmin), arg0)
}

// LogoutRefreshToken mocks base method.
func (m *MockKeycloakClient) LogoutRefreshToken(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogoutRefreshToken indicates an expected call of LogoutRefreshToken.
func (mr *MockKeycloakClientMockRecorder) LogoutRefreshToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutRefreshToken", reflect.TypeOf((*MockKeycloakClient)(nil).LogoutRefreshToken), arg0, arg1)
}

// PasswordGrant mocks base method.
func (m *MockKeycloakClient) PasswordGrant(arg0 context.Context, arg1, arg2 string) (*ports.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordGrant", arg0, arg1, arg2)
	ret0, _ := ret[0].(*ports.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasswordGrant indicates an expected call of PasswordGrant.
func (mr *MockKeycloakClientMockRecorder) PasswordGrant(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordGrant", reflect.TypeOf((*MockKeycloakClient)(nil).PasswordGrant), arg0, arg1, arg2)
}

// RealmRole mocks base method.
func (m *MockKeycloakClient) RealmRole(arg0 context.Context, arg1, arg2 string) (*gocloak.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RealmRole", arg0, arg1, arg2)
	ret0, _ := ret[0].(*gocloak.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RealmRole indicates an expected call of RealmRole.
func (mr *MockKeycloakClientMockRecorder) RealmRole(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RealmRole", reflect.TypeOf((*MockKeycloakClient)(nil).RealmRole), arg0, arg1, arg2)
}

// RefreshToken mocks base method.
func (m *MockKeycloakClient) RefreshToken(arg0 context.Context, arg1 string) (*ports.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", arg0, arg1)
	ret0, _ := ret[0].(*ports.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockKeycloakClientMockRecorder) RefreshToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockKeycloakClient)(nil).RefreshToken), arg0, arg1)
}

// RemoveUserFromGroup mocks base method.
func (m *MockKeycloakClient) RemoveUserFromGroup(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromGroup", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromGroup indicates an expected call of RemoveUserFromGroup.
func (mr *MockKeycloakClientMockRecorder) RemoveUserFromGroup(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromGroup", reflect.TypeOf((*MockKeycloakClient)(nil).RemoveUserFromGroup), arg0, arg1, arg2, arg3)
}

// SetRealmRolesForUser mocks base method.
func (m *MockKeycloakClient) SetRealmRolesForUser(arg0 context.Context, arg1, arg2 string, arg3 []gocloak.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRealmRolesForUser", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRealmRolesForUser indicates an expected call of SetRealmRolesForUser.
func (mr *MockKeycloakClientMockRecorder) SetRealmRolesForUser(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRealmRolesForUser", reflect.TypeOf((*MockKeycloakClient)(nil).SetRealmRolesForUser), arg0, arg1, arg2, arg3)
}

// SetUserPassword mocks base method.
func (m *MockKeycloakClient) SetUserPassword(arg0 context.Context, arg1, arg2, arg3 string, arg4 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserPassword", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserPassword indicates an expected call of SetUserPassword.
func (mr *MockKeycloakClientMockRecorder) SetUserPassword(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserPassword", reflect.TypeOf((*MockKeycloakClient)(nil).SetUserPassword), arg0, arg1, arg2, arg3, arg4)
}
