// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/industrial-sed/auth-service/internal/usecases (interfaces: TenantRepository,UserCacheRepository,Notifier)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/repos.go -package=mocks github.com/industrial-sed/auth-service/internal/usecases TenantRepository,UserCacheRepository,Notifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/industrial-sed/auth-service/internal/models"
	usecases "github.com/industrial-sed/auth-service/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantRepository) Create(arg0 context.Context, arg1 *models.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTenantRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockTenantRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantRepositoryMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantRepository)(nil).Delete), arg0, arg1)
}

// GetByCode mocks base method.
func (m *MockTenantRepository) GetByCode(arg0 context.Context, arg1 string) (*models.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", arg0, arg1)
	ret0, _ := ret[0].(*models.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockTenantRepositoryMockRecorder) GetByCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockTenantRepository)(nil).GetByCode), arg0, arg1)
}

// List mocks base method.
func (m *MockTenantRepository) List(arg0 context.Context) ([]models.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]models.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTenantRepositoryMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantRepository)(nil).List), arg0)
}

// ListByCodePrefix mocks base method.
func (m *MockTenantRepository) ListByCodePrefix(arg0 context.Context, arg1 string) ([]models.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCodePrefix", arg0, arg1)
	ret0, _ := ret[0].([]models.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCodePrefix indicates an expected call of ListByCodePrefix.
func (mr *MockTenantRepositoryMockRecorder) ListByCodePrefix(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCodePrefix", reflect.TypeOf((*MockTenantRepository)(nil).ListByCodePrefix), arg0, arg1)
}

// MockUserCacheRepository is a mock of UserCacheRepository interface.
type MockUserCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheRepositoryMockRecorder
}

// MockUserCacheRepositoryMockRecorder is the mock recorder for MockUserCacheRepository.
type MockUserCacheRepositoryMockRecorder struct {
	mock *MockUserCacheRepository
}

// NewMockUserCacheRepository creates a new mock instance.
func NewMockUserCacheRepository(ctrl *gomock.Controller) *MockUserCacheRepository {
	mock := &MockUserCacheRepository{ctrl: ctrl}
	mock.recorder = &MockUserCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCacheRepository) EXPECT() *MockUserCacheRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserCacheRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserCacheRepositoryMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserCacheRepository)(nil).Delete), arg0, arg1)
}

// DeleteByTenant mocks base method.
func (m *MockUserCacheRepository) DeleteByTenant(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTenant", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTenant indicates an expected call of DeleteByTenant.
func (mr *MockUserCacheRepositoryMockRecorder) DeleteByTenant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTenant", reflect.TypeOf((*MockUserCacheRepository)(nil).DeleteByTenant), arg0, arg1)
}

// GetByKeycloakID mocks base method.
func (m *MockUserCacheRepository) GetByKeycloakID(arg0 context.Context, arg1 string) (*models.UserCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKeycloakID", arg0, arg1)
	ret0, _ := ret[0].(*models.UserCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKeycloakID indicates an expected call of GetByKeycloakID.
func (mr *MockUserCacheRepositoryMockRecorder) GetByKeycloakID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKeycloakID", reflect.TypeOf((*MockUserCacheRepository)(nil).GetByKeycloakID), arg0, arg1)
}

// ListByTenant mocks base method.
func (m *MockUserCacheRepository) ListByTenant(arg0 context.Context, arg1 string) ([]models.UserCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenant", arg0, arg1)
	ret0, _ := ret[0].([]models.UserCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenant indicates an expected call of ListByTenant.
func (mr *MockUserCacheRepositoryMockRecorder) ListByTenant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenant", reflect.TypeOf((*MockUserCacheRepository)(nil).ListByTenant), arg0, arg1)
}

// Upsert mocks base method.
func (m *MockUserCacheRepository) Upsert(arg0 context.Context, arg1 *models.UserCache) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockUserCacheRepositoryMockRecorder) Upsert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockUserCacheRepository)(nil).Upsert), arg0, arg1)
}

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyUserCreated mocks base method.
func (m *MockNotifier) NotifyUserCreated(arg0 context.Context, arg1 usecases.UserCreatedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyUserCreated", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyUserCreated indicates an expected call of NotifyUserCreated.
func (mr *MockNotifierMockRecorder) NotifyUserCreated(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyUserCreated", reflect.TypeOf((*MockNotifier)(nil).NotifyUserCreated), arg0, arg1)
}
